export const PERM = {
  ADMIN_ALL: "ADMIN_ALL",

  AUDIT_READ: "AUDIT_READ",

  DASHBOARD_VIEW: "DASHBOARD_VIEW",
  FARM_VIEW: "FARM_VIEW",
  FARM_MANAGE: "FARM_MANAGE",

  POULTRY_VIEW: "POULTRY_VIEW",
  POULTRY_MANAGE: "POULTRY_MANAGE",

  LAYERS_VIEW: "LAYERS_VIEW",
  LAYERS_MANAGE: "LAYERS_MANAGE",
  LAYERS_RECORD_PRODUCTION: "LAYERS_RECORD_PRODUCTION",

  BROILERS_VIEW: "BROILERS_VIEW",
  BROILERS_MANAGE: "BROILERS_MANAGE",
  BROILERS_RECORD_PRODUCTION: "BROILERS_RECORD_PRODUCTION",

  BREEDERS_VIEW: "BREEDERS_VIEW",
  BREEDERS_MANAGE: "BREEDERS_MANAGE",
  BREEDERS_RECORD: "BREEDERS_RECORD",

  HATCHERY_VIEW: "HATCHERY_VIEW",
  HATCHERY_MANAGE: "HATCHERY_MANAGE",
  HATCHERY_RECORD: "HATCHERY_RECORD",

  FEED_VIEW: "FEED_VIEW",
  FEED_MANAGE: "FEED_MANAGE",
  FEED_ISSUE: "FEED_ISSUE",
  FEED_PRODUCE: "FEED_PRODUCE",

  HEALTH_VIEW: "HEALTH_VIEW",
  HEALTH_RECORD: "HEALTH_RECORD",
  BIOSECURITY_VIEW: "BIOSECURITY_VIEW",
  BIOSECURITY_RECORD: "BIOSECURITY_RECORD",

  EGGROOM_VIEW: "EGGROOM_VIEW",
  EGGROOM_RECORD: "EGGROOM_RECORD",
  PROCESSING_VIEW: "PROCESSING_VIEW",
  PROCESSING_RECORD: "PROCESSING_RECORD",

  CROPS_VIEW: "CROPS_VIEW",
  CROPS_MANAGE: "CROPS_MANAGE",

  YAM_VIEW: "YAM_VIEW",
  YAM_MANAGE: "YAM_MANAGE",
  YAM_RECORD: "YAM_RECORD",

  PLANTAIN_VIEW: "PLANTAIN_VIEW",
  PLANTAIN_MANAGE: "PLANTAIN_MANAGE",
  PLANTAIN_RECORD: "PLANTAIN_RECORD",

  OILPALM_VIEW: "OILPALM_VIEW",
  OILPALM_MANAGE: "OILPALM_MANAGE",
  OILPALM_RECORD: "OILPALM_RECORD",

  BLOCKS_VIEW: "BLOCKS_VIEW",
  BLOCKS_MANAGE: "BLOCKS_MANAGE",
  FIELDOPS_VIEW: "FIELDOPS_VIEW",
  FIELDOPS_RECORD: "FIELDOPS_RECORD",

  IRRIGATION_VIEW: "IRRIGATION_VIEW",
  IRRIGATION_MANAGE: "IRRIGATION_MANAGE",
  IRRIGATION_RUN_LOG: "IRRIGATION_RUN_LOG",

  FARM_INV_VIEW: "FARM_INV_VIEW",
  FARM_INV_MANAGE: "FARM_INV_MANAGE",

  FIN_VIEW: "FIN_VIEW",
  FIN_POST: "FIN_POST",
  FIN_APPROVE: "FIN_APPROVE",
  FIN_LOCK_PERIOD: "FIN_LOCK_PERIOD",
  REPORTS_VIEW: "REPORTS_VIEW",

  STORE_VIEW: "STORE_VIEW",
  STORE_MANAGE: "STORE_MANAGE",

  POS_VIEW: "POS_VIEW",
  POS_SALE: "POS_SALE",
  POS_REFUND: "POS_REFUND",
  POS_DISCOUNT: "POS_DISCOUNT",
  POS_CASHUP: "POS_CASHUP",

  STORE_INV_VIEW: "STORE_INV_VIEW",
  STORE_INV_RECEIVE: "STORE_INV_RECEIVE",
  STORE_INV_ADJUST: "STORE_INV_ADJUST",
  STORE_INV_COUNT: "STORE_INV_COUNT",

  TRANSFERS_VIEW: "TRANSFERS_VIEW",
  TRANSFERS_CREATE: "TRANSFERS_CREATE",
  TRANSFERS_APPROVE: "TRANSFERS_APPROVE",
  RETURNS_VIEW: "RETURNS_VIEW",
  RETURNS_CREATE: "RETURNS_CREATE",
  RETURNS_APPROVE: "RETURNS_APPROVE",

  CATALOG_VIEW: "CATALOG_VIEW",
  PRICING_SET: "PRICING_SET",

  CUSTOMERS_VIEW: "CUSTOMERS_VIEW",
  CUSTOMERS_MANAGE: "CUSTOMERS_MANAGE",

  LOGISTICS_VIEW: "LOGISTICS_VIEW",
  LOGISTICS_MANAGE: "LOGISTICS_MANAGE",
  DISPATCH_VIEW: "DISPATCH_VIEW",
  DISPATCH_CREATE: "DISPATCH_CREATE",
  POD_CONFIRM: "POD_CONFIRM",

  HR_VIEW: "HR_VIEW",
  HR_MANAGE: "HR_MANAGE",
  PAYROLL_INPUT: "PAYROLL_INPUT",

  COMMISSION_VIEW: "COMMISSION_VIEW",
  COMMISSION_MANAGE: "COMMISSION_MANAGE",

  COMMISSION_AGENTS_VIEW: "COMMISSION_AGENTS_VIEW",
  COMMISSION_AGENTS_MANAGE: "COMMISSION_AGENTS_MANAGE",

  COMMISSION_RULES_VIEW: "COMMISSION_RULES_VIEW",
  COMMISSION_RULES_MANAGE: "COMMISSION_RULES_MANAGE",

  COMMISSION_ORDERS_VIEW: "COMMISSION_ORDERS_VIEW",
  COMMISSION_ORDERS_RECONCILE: "COMMISSION_ORDERS_RECONCILE",

  COMMISSION_APPROVE: "COMMISSION_APPROVE", // approve claim/payout
  COMMISSION_PAYOUTS_VIEW: "COMMISSION_PAYOUTS_VIEW",
  COMMISSION_PAYOUTS_RUN: "COMMISSION_PAYOUTS_RUN",

  COMMISSION_DISPUTES_VIEW: "COMMISSION_DISPUTES_VIEW",
  COMMISSION_DISPUTES_MANAGE: "COMMISSION_DISPUTES_MANAGE",

  COMMISSION_REPORTS_VIEW: "COMMISSION_REPORTS_VIEW",

  COMMISSION_SETTINGS_MANAGE: "COMMISSION_SETTINGS_MANAGE",



};
