import { PERM } from "./perms";

export const ROLE = {
  SUPER_ADMIN: "SUPER_ADMIN",
  GROUP_FINANCE_DIRECTOR: "GROUP_FINANCE_DIRECTOR",
  FARM_ADMIN: "FARM_ADMIN",
  POULTRY_MANAGER: "POULTRY_MANAGER",
  CROP_MANAGER: "CROP_MANAGER",
  IRRIGATION_OFFICER: "IRRIGATION_OFFICER",
  FARM_ACCOUNTANT: "FARM_ACCOUNTANT",
  STORE_MANAGER: "STORE_MANAGER",
  CASHIER: "CASHIER",
  STORE_INVENTORY_OFFICER: "STORE_INVENTORY_OFFICER",
  LOGISTICS_MANAGER: "LOGISTICS_MANAGER",
  DRIVER: "DRIVER",
  HR_MANAGER: "HR_MANAGER",
  AUDITOR: "AUDITOR"
};

export const ROLE_PERMISSIONS = {
  [ROLE.SUPER_ADMIN]: [PERM.ADMIN_ALL],

  [ROLE.GROUP_FINANCE_DIRECTOR]: [
    PERM.FARM_VIEW, PERM.STORE_VIEW,
    PERM.FIN_VIEW, PERM.FIN_POST, PERM.FIN_APPROVE, PERM.FIN_LOCK_PERIOD,
    PERM.REPORTS_VIEW
  ],

  [ROLE.FARM_ADMIN]: [
    PERM.FARM_VIEW, PERM.FARM_MANAGE,
    PERM.POULTRY_VIEW, PERM.POULTRY_MANAGE,
    PERM.LAYERS_VIEW, PERM.LAYERS_MANAGE, PERM.LAYERS_RECORD_PRODUCTION,
    PERM.BROILERS_VIEW, PERM.BROILERS_MANAGE, PERM.BROILERS_RECORD_PRODUCTION,
    PERM.BREEDERS_VIEW, PERM.BREEDERS_MANAGE, PERM.BREEDERS_RECORD,
    PERM.HATCHERY_VIEW, PERM.HATCHERY_MANAGE, PERM.HATCHERY_RECORD,
    PERM.FEED_VIEW, PERM.FEED_MANAGE, PERM.FEED_ISSUE, PERM.FEED_PRODUCE,
    PERM.HEALTH_VIEW, PERM.HEALTH_RECORD,
    PERM.BIOSECURITY_VIEW, PERM.BIOSECURITY_RECORD,
    PERM.EGGROOM_VIEW, PERM.EGGROOM_RECORD,
    PERM.PROCESSING_VIEW, PERM.PROCESSING_RECORD,
    PERM.CROPS_VIEW, PERM.CROPS_MANAGE,
    PERM.YAM_VIEW, PERM.YAM_MANAGE, PERM.YAM_RECORD,
    PERM.PLANTAIN_VIEW, PERM.PLANTAIN_MANAGE, PERM.PLANTAIN_RECORD,
    PERM.OILPALM_VIEW, PERM.OILPALM_MANAGE, PERM.OILPALM_RECORD,
    PERM.BLOCKS_VIEW, PERM.BLOCKS_MANAGE,
    PERM.FIELDOPS_VIEW, PERM.FIELDOPS_RECORD,
    PERM.IRRIGATION_VIEW, PERM.IRRIGATION_MANAGE, PERM.IRRIGATION_RUN_LOG,
    PERM.FARM_INV_VIEW, PERM.FARM_INV_MANAGE,
    PERM.FIN_VIEW, PERM.FIN_POST,
    PERM.REPORTS_VIEW
  ],

  [ROLE.POULTRY_MANAGER]: [
    PERM.FARM_VIEW, PERM.POULTRY_VIEW,
    PERM.LAYERS_VIEW, PERM.LAYERS_RECORD_PRODUCTION,
    PERM.BROILERS_VIEW, PERM.BROILERS_RECORD_PRODUCTION,
    PERM.BREEDERS_VIEW, PERM.BREEDERS_RECORD,
    PERM.HATCHERY_VIEW, PERM.HATCHERY_RECORD,
    PERM.FEED_VIEW, PERM.FEED_ISSUE,
    PERM.HEALTH_VIEW, PERM.HEALTH_RECORD,
    PERM.BIOSECURITY_VIEW, PERM.BIOSECURITY_RECORD,
    PERM.EGGROOM_VIEW, PERM.EGGROOM_RECORD
  ],

  [ROLE.CROP_MANAGER]: [
    PERM.FARM_VIEW,
    PERM.CROPS_VIEW, PERM.CROPS_MANAGE,
    PERM.YAM_VIEW, PERM.YAM_RECORD,
    PERM.PLANTAIN_VIEW, PERM.PLANTAIN_RECORD,
    PERM.OILPALM_VIEW, PERM.OILPALM_RECORD,
    PERM.BLOCKS_VIEW, PERM.BLOCKS_MANAGE,
    PERM.FIELDOPS_VIEW, PERM.FIELDOPS_RECORD,
    PERM.IRRIGATION_VIEW
  ],

  [ROLE.IRRIGATION_OFFICER]: [
    PERM.FARM_VIEW,
    PERM.IRRIGATION_VIEW, PERM.IRRIGATION_MANAGE, PERM.IRRIGATION_RUN_LOG
  ],

  [ROLE.FARM_ACCOUNTANT]: [
    PERM.FARM_VIEW,
    PERM.FIN_VIEW, PERM.FIN_POST,
    PERM.REPORTS_VIEW
  ],

  [ROLE.STORE_MANAGER]: [
    PERM.STORE_VIEW, PERM.STORE_MANAGE,
    PERM.POS_VIEW, PERM.POS_SALE, PERM.POS_REFUND, PERM.POS_DISCOUNT, PERM.POS_CASHUP,
    PERM.STORE_INV_VIEW, PERM.STORE_INV_RECEIVE, PERM.STORE_INV_ADJUST, PERM.STORE_INV_COUNT,
    PERM.TRANSFERS_VIEW, PERM.TRANSFERS_CREATE, PERM.TRANSFERS_APPROVE,
    PERM.RETURNS_VIEW, PERM.RETURNS_CREATE, PERM.RETURNS_APPROVE,
    PERM.CATALOG_VIEW, PERM.PRICING_SET,
    PERM.CUSTOMERS_VIEW, PERM.CUSTOMERS_MANAGE,
    PERM.FIN_VIEW, PERM.REPORTS_VIEW
  ],

  [ROLE.CASHIER]: [
    PERM.STORE_VIEW,
    PERM.POS_VIEW, PERM.POS_SALE,
    PERM.CUSTOMERS_VIEW
  ],

  [ROLE.STORE_INVENTORY_OFFICER]: [
    PERM.STORE_VIEW,
    PERM.STORE_INV_VIEW, PERM.STORE_INV_RECEIVE, PERM.STORE_INV_COUNT,
    PERM.TRANSFERS_VIEW, PERM.TRANSFERS_CREATE,
    PERM.RETURNS_VIEW, PERM.RETURNS_CREATE
  ],

  [ROLE.LOGISTICS_MANAGER]: [
    PERM.LOGISTICS_VIEW, PERM.LOGISTICS_MANAGE,
    PERM.DISPATCH_VIEW, PERM.DISPATCH_CREATE,
    PERM.TRANSFERS_VIEW,
    PERM.FARM_VIEW, PERM.STORE_VIEW
  ],

  [ROLE.DRIVER]: [
    PERM.LOGISTICS_VIEW, PERM.DISPATCH_VIEW, PERM.POD_CONFIRM
  ],

  [ROLE.HR_MANAGER]: [
    PERM.HR_VIEW, PERM.HR_MANAGE, PERM.PAYROLL_INPUT
  ],

  [ROLE.AUDITOR]: [
    PERM.AUDIT_READ,
    PERM.FARM_VIEW, PERM.STORE_VIEW,
    PERM.POULTRY_VIEW, PERM.CROPS_VIEW, PERM.IRRIGATION_VIEW,
    PERM.FIN_VIEW, PERM.REPORTS_VIEW,
    PERM.LOGISTICS_VIEW,
    PERM.HR_VIEW,
    PERM.CATALOG_VIEW,
    PERM.POS_VIEW,
    PERM.TRANSFERS_VIEW,
    PERM.RETURNS_VIEW
  ]
};
